# Copyright the Hyperledger Fabric contributors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: Scheduled build

on:
  schedule:
    - cron: "5 4 * * 0"   # Sunday 04:05 UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  main:
    uses: ./.github/workflows/test.yml
